apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{PROJECT}}-volume
spec:
  capacity:
    storage: 5Gi
  local:
    path: /k8s-data/{{PROJECT}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 501st